# Interactive Windows/OpenGL verification, intentionally separate from normal CTest.
# Choose a fresh IROP_WORK_DIR; this script never removes existing directories.
cmake_minimum_required(VERSION 4.2)

if(NOT WIN32)
    message(FATAL_ERROR "Studio desktop smoke verification requires Windows")
endif()
foreach(required_variable IN ITEMS IROP_STUDIO_EXECUTABLE IROP_OBJECT_FIXTURE IROP_CONTAINER_FIXTURE IROP_WORK_DIR)
    if(NOT DEFINED ${required_variable} OR "${${required_variable}}" STREQUAL "")
        message(FATAL_ERROR "${required_variable} must be provided to the Studio smoke driver")
    endif()
endforeach()
foreach(input_variable IN ITEMS IROP_STUDIO_EXECUTABLE IROP_OBJECT_FIXTURE IROP_CONTAINER_FIXTURE)
    cmake_path(ABSOLUTE_PATH ${input_variable} BASE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}" NORMALIZE)
    if(NOT EXISTS "${${input_variable}}" OR IS_DIRECTORY "${${input_variable}}")
        message(FATAL_ERROR "${input_variable} must name an existing file")
    endif()
    file(REAL_PATH "${${input_variable}}" ${input_variable})
endforeach()
cmake_path(ABSOLUTE_PATH IROP_WORK_DIR NORMALIZE OUTPUT_VARIABLE work_directory)
if(EXISTS "${work_directory}" OR IS_SYMLINK "${work_directory}")
    message(FATAL_ERROR "Studio smoke output must be a fresh directory: ${work_directory}")
endif()
file(MAKE_DIRECTORY "${work_directory}")

function(run_studio action expected_status expect_image)
    set(action_directory "${work_directory}/${action}")
    set(extra_arguments ${ARGN})
    set(smoke_action "${action}")
    if(action STREQUAL "malformed")
        set(smoke_action "open")
    endif()
    message(STATUS "Studio desktop smoke: ${action}")
    execute_process(
        COMMAND "${IROP_STUDIO_EXECUTABLE}"
            --object "${IROP_OBJECT_FIXTURE}"
            --container "${IROP_CONTAINER_FIXTURE}"
            --smoke-test "${action_directory}"
            --smoke-action "${smoke_action}"
            ${extra_arguments}
        RESULT_VARIABLE actual_exit
        OUTPUT_VARIABLE command_stdout
        ERROR_VARIABLE command_stderr
        TIMEOUT 90
    )
    if(NOT "${actual_exit}" MATCHES "^-?[0-9]+$" OR NOT actual_exit EQUAL 0)
        message(FATAL_ERROR
            "Studio ${action} did not exit normally: ${actual_exit}\nstdout:\n${command_stdout}\nstderr:\n${command_stderr}")
    endif()
    if(EXISTS "${action_directory}/smoke-error.txt")
        file(READ "${action_directory}/smoke-error.txt" error_text LIMIT 8192)
        message(FATAL_ERROR "Studio ${action} reported an application error: ${error_text}")
    endif()
    if(NOT EXISTS "${action_directory}/smoke-result.txt")
        message(FATAL_ERROR "Studio ${action} did not publish its completion report")
    endif()
    file(STRINGS "${action_directory}/smoke-result.txt" status LIMIT_COUNT 1)
    if(NOT status STREQUAL expected_status)
        file(READ "${action_directory}/smoke-result.txt" report_text LIMIT 8192)
        message(FATAL_ERROR "Studio ${action}: expected ${expected_status}, received ${report_text}")
    endif()
    if(expect_image)
        if(NOT EXISTS "${action_directory}/viewport.png")
            message(FATAL_ERROR "Studio ${action} did not capture rendered geometry")
        endif()
        file(READ "${action_directory}/viewport.png" signature LIMIT 8 HEX)
        file(SIZE "${action_directory}/viewport.png" png_size)
        if(NOT signature STREQUAL "89504e470d0a1a0a" OR png_size LESS 256)
            message(FATAL_ERROR "Studio ${action} viewport capture is not a nonempty PNG")
        endif()
    elseif(EXISTS "${action_directory}/viewport.png")
        message(FATAL_ERROR "Studio ${action} incorrectly presented geometry for a failed/cancelled load")
    endif()
endfunction()

run_studio(preview input_preview TRUE)
run_studio(pack success TRUE)
set(packed_directory "${work_directory}/pack/run")
foreach(artifact IN ITEMS packed-objects.stl container.stl placements.json run-summary.json)
    if(NOT EXISTS "${packed_directory}/${artifact}" OR IS_DIRECTORY "${packed_directory}/${artifact}")
        message(FATAL_ERROR "Studio packing did not publish ${artifact}")
    endif()
endforeach()
file(READ "${packed_directory}/run-summary.json" packed_summary LIMIT 16777216)
string(JSON packed_status GET "${packed_summary}" outcome category)
string(JSON physical_valid GET "${packed_summary}" validation physical_scene_valid)
string(JSON solve_count GET "${packed_summary}" work local_solves)
string(JSON initial_scale GET "${packed_summary}" config initial_volume_scale)
string(JSON final_scale GET "${packed_summary}" config final_volume_scale)
if(NOT packed_status STREQUAL "success" OR NOT physical_valid OR solve_count LESS 1 OR
   NOT initial_scale EQUAL 0.1 OR NOT final_scale EQUAL 0.2)
    message(FATAL_ERROR "Studio packing did not complete the expected genuine .1 -> .2 growth run")
endif()
run_studio(open success TRUE --open "${packed_directory}/run-summary.json")

foreach(action IN ITEMS cancel close-active)
    run_studio("${action}" cancelled FALSE)
    set(cancelled_directory "${work_directory}/${action}/run")
    if(EXISTS "${cancelled_directory}")
        file(GLOB artifacts RELATIVE "${cancelled_directory}" "${cancelled_directory}/*")
        if(NOT artifacts STREQUAL "run-summary.json")
            message(FATAL_ERROR "Studio ${action} published success or unexpected artifacts: ${artifacts}")
        endif()
        file(READ "${cancelled_directory}/run-summary.json" cancelled_summary LIMIT 16777216)
        string(JSON cancelled_status GET "${cancelled_summary}" outcome category)
        if(NOT cancelled_status STREQUAL "cancelled")
            message(FATAL_ERROR "Studio ${action} summary did not preserve the cancelled outcome")
        endif()
    endif()
endforeach()

file(WRITE "${work_directory}/malformed-summary.json" "{\"schema_version\":")
run_studio(malformed error FALSE --open "${work_directory}/malformed-summary.json")
message(STATUS "Studio desktop smoke passed. Reports and viewport captures: ${work_directory}")
